### ISSUE TITLE
Error on <TAB>

### ISSUE THREAD

**Issue by zoranzaric** [jceb/vim-orgmode#111]
in a file like
     \* foo
        \* bar

hitting <TAB> on the first line results in this error:

``````
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/zz/.vim/bundle/vim-orgmode/ftplugin/orgmode/__init__.py", line 79, in r
    res = f(*args, **kwargs)
  File "/home/zz/.vim/bundle/vim-orgmode/ftplugin/orgmode/plugins/ShowHide.py", line 91, in toggle_folding
    vim.command((u'%d,%dfoldclose!' % (heading.start_vim, heading.end_of_last_child_vim)).encode(u'utf-8'))
vim.error```
``````

OS is GNU/Linux, distribution is Archl, Vim version is 7.3

**Comment by triplejay2013** [comment]
Thought I would comment for others who might encounter this issue. I had (prior to vim-orgmode) customized foldmethod to something else. Using `set foldmethod=manual` resolved visibility cycling issues.

**Comment by zdehghan** [comment]
Hi all. I have a similar folding problem. It was working fine and I think after installing `YouCompleteMe` plugin the problem has occured. I have deleted all the `*pyc` files that were installed in my `~/.vim` directory - all by `YouCompleteMe` but that didn't help.

`Error detected while processing :
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/zdehghanm/.vim/bundle/vim-orgmode/ftplugin/orgmode/_vim.py", line 85, in r
    res = f(*args, **kwargs)
  File "/Users/zdehghanm/.vim/bundle/vim-orgmode/ftplugin/orgmode/plugins/ShowHide.py", line 104, in toggle_folding
    vim.command(u_encode(u'%d,%dfoldclose!' % (heading.start_vim, heading.end_of_last_child_vim)))
vim.error: Vim(foldclose):E490: No fold found`

I appreciate your help!

**Comment by zdehghan** [comment]
The culprit is this plugin `Plugin 'inkarkat/vim-SyntaxRange`, don't know why.
