### ISSUE TITLE
agenda view shows nothing

### ISSUE THREAD

**Issue by Bruno-Sosa** [jceb/vim-orgmode#227]
Whenever I type `-caa` (where `-` is my localleader) I get the following message:

```python
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/xxxx/.vim/ftplugin/orgmode/plugins/Agenda.py", line 152, in list_next_week
    last_date = raw_agenda[0].active_date
IndexError: list index out of range
```

I can't figure it out. I looked at the [mentioned line][0], and where [raw_agenda][1] is defined.
`ORGMODE.agenda_manager` is [imported][6] from [here][2], which calls `AgendaManager()`.
Looking at the [imports][3] leads me to where `.get_next_week_and_active_todo` is [defined][4].
(yes the todos are active and within this week, it works fine in emacs org-mode)
It is being [called][1] with `agenda_documents`, which is defined [here][5].
I have no idea what`cls` is or what is calling `list_next_week`  in the first place

[0]: https://github.com/jceb/vim-orgmode/blob/master/ftplugin/orgmode/plugins/Agenda.py#L157
[1]: https://github.com/jceb/vim-orgmode/blob/master/ftplugin/orgmode/plugins/Agenda.py#L140
[2]: https://github.com/jceb/vim-orgmode/blob/master/ftplugin/orgmode/_vim.py#L286
[3]:https://github.com/jceb/vim-orgmode/blob/master/ftplugin/orgmode/_vim.py#L23
[4]: https://github.com/jceb/vim-orgmode/blob/master/ftplugin/orgmode/liborgmode/agenda.py#L38
[5]: https://github.com/jceb/vim-orgmode/blob/master/ftplugin/orgmode/plugins/Agenda.py#L137
[6]:https://github.com/jceb/vim-orgmode/blob/master/ftplugin/orgmode/plugins/Agenda.py#L9

**Comment by Bruno-Sosa** [comment]
I sorry if I mixed up my terminology, as I'm not a programmer (know a bit a python, but definitely not OOP). I'm running Arch Linux if that helps.

**Comment by Ron89** [comment]
I fixed the out of range problem with a simple fix few days ago. Please update and see if the issue still exists?

The main reason is when there is no matched agenda, `raw_agenda` is empty. Yet the empty array was not handled properly.

**Comment by Ron89** [comment]
Also, you also need to setup your agenda files with `let g:org_agenda_files=['list', 'of'. 'files']`, e.g.,

```
  let g:org_agenda_files=['~/research_Documents/research/journal.org', '~/projects/todo-list.org']

```

**Comment by Bruno-Sosa** [comment]
ok thank you!  I did set my agenda files, but since I just started I choose only one. To update I download from [here][0] and unzip it to `~/.vim/` right?

[0]: https://github.com/jceb/vim-orgmode/releases

**Comment by Ron89** [comment]
Oh, no. The new changes are not released yet. I suggest you use [vim-plug](https://github.com/junegunn/vim-plug) to install it. vim-plug is a good plugin-manager.

Add the line
```
Plug 'jceb/vim-orgmode'
```
In your `.vimrc` after installing vim-plug and invoke
```
:PlugInstall
```

**Comment by Bruno-Sosa** [comment]
ha, ok guess one more package won't hurt :)  (at least its minimalist) Thank you anyways.
