### ISSUE TITLE
<ll>ft errors

### ISSUE THREAD

**Issue by memeplex** [jceb/vim-orgmode#247]
The find tags feature is not giving any completion and I get this error after entering some tag:

```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/carlos/.vim/bundle/vim-orgmode/ftplugin/orgmode/plugins/TagsProperties.py", line 106, in find_tags
    tags = vim.eval(u'input("Find Tags: ", "", "customlist,Org_complete_tags")')
vim.error: Vim(python):Traceback (most recent call last):
```

**Comment by memeplex** [comment]
Not sure whether this is of some help but when I call `input("Find Tags: ", "", "customlist,Org_complete_tags")` from the command line I get:

```
Error detected while processing function Org_complete_tags:                                                                                                               
line    3:                                                                                                                                                                
Traceback (most recent call last):                                                                                                                                        
  File "<string>", line 1, in <module>                                                                                                                                    
NameError: name 'ORGMODE' is not defined  
```

**Comment by memeplex** [comment]
I think this was because I installed vim-orgmode the pathogen way. Reinstalling from vba fixed the issue. Feel free to close this but first I would like to know if it's possible to install this plugin as a separate bundle, I don't like mixing the files of different plugins.

**Comment by memeplex** [comment]
Forget about my last comment: it wasn't a matter of vimball vs pathogen, a bundle using the v0.5.0 tag worked just fine. So there seems to be a bug in master after all.

**Comment by jceb** [comment]
Thanks for reporting.  Pull requests are welcome

**Comment by doak** [comment]
@memeplex, your bug report was some time ago. Do you still have that issue?

I am also using *Pathogen* and I don't experience that issue (with `v0.6.0-28-gc6cd668`), though there are similar issue for `v0.6.0` and even more for `v0.5.0` (as far as I could test it).

Probably this issue can be closed now. Please give some short notice, @memeplex.
