### ISSUE TITLE
Agenda error

### ISSUE THREAD

**Issue by rgc69** [jceb/vim-orgmode#259]
Hi Jan, the weekly/daily agenda command <LocalLeader>caa return this error:

Traceback (most recent call last):
  File "<string>", line 1, in <module>
    File "~/.vim/ftplugin/orgmode/plugins/Agenda.py", line 152, in
    list_next_week
        last_date = raw_agenda[0].active_date
        IndexError: list index out of range

The global TODO list command <LocalLeader>cat it's ok. Any idea? Thank you!

**Comment by jceb** [comment]
Hi, thanks for reporting the issue.  Would you investigate the issue a little more and provide a pull request?

**Comment by JaniM** [comment]
Reproduced with an org file that has a single timestamped item

```
* Foo <2020-09-01 Tue>
```

Having headers before this does not affect the error. Having a non-timestamped entry after it gets rid of it.
