### ISSUE TITLE
TODO list mapping throws error

### ISSUE THREAD

**Issue by stsievert** [jceb/vim-orgmode#267]
In an org file with neovim, `<localleader>cat` should show the TODO list. Instead,

``` traceback
Error detected while processing function provider#python3#Call:
line   18:
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/scott/.config/nvim/plugged/vim-orgmode/ftplugin/orgmode/plugins/Agenda.py", line 226, in list_all_todos
    loaded_agendafiles = cls._get_agendadocuments()
  File "/Users/scott/.config/nvim/plugged/vim-orgmode/ftplugin/orgmode/plugins/Agenda.py", line 79, in _get_agendadocuments
    u"No org_agenda_files defined. Use :let "
  File "/Users/scott/.config/nvim/plugged/vim-orgmode/ftplugin/orgmode/_vim.py", line 119, in echoe
    vim.command(u_encode(u':echoerr "%s"' % m))
  File "/Users/scott/anaconda/lib/python3.5/site-packages/neovim/api/nvim.py", line 218, in command
    return self.request('nvim_command', string, **kwargs)
  File "/Users/scott/anaconda/lib/python3.5/site-packages/neovim/api/nvim.py", line 131, in request
    res = self._session.request(name, *args, **kwargs)
  File "/Users/scott/anaconda/lib/python3.5/site-packages/neovim/msgpack_rpc/session.py", line 98, in request
    raise self.error_wrapper(e
```

**Comment by hrafeiro** [comment]
Same issue here. Both in MacOSX and Lubuntu I've the same error. Anyone can help?

**Comment by sotte** [comment]
@hrafeiro @stsievert 
The errors is kinda hidden. `No org_agenda_files defined`.

Use `:let org_agenda_fiels = ['~/org/file_for_agenda']` and try again.

I guess org should fail gracefully.

**Comment by timjstewart** [comment]
Slight edit: 
s/fiels/files/
