### ISSUE TITLE
TODO fast access prompt throws error

### ISSUE THREAD

**Issue by Liriel** [jceb/vim-orgmode#274]
with vim 8.0 on windows x64 using python 2.7 when pressing `<localleader>d` I get:

> 2 more lines; before #95  1 seconds ago
> 
> Error detected while processing :
> Traceback (most recent call last):
>   File "<string>", line 1, in <module>
>   File "C:\Users\jim/vimfiles\ftplugin\orgmode\_vim.py", line 37, in r
>     res = f(*args, **kwargs)
>   File "C:\Users\jim/vimfiles\ftplugin\orgmode\_vim.py", line 57, in r
>     res = f(*args, **kwargs)
>   File "C:\Users\jim/vimfiles\ftplugin\orgmode\_vim.py", line 82, in r
>     res = f(*args, **kwargs)
>   File "C:\Users\jim/vimfiles\ftplugin\orgmode\plugins\Todo.py", line 185, in toggle_todo_state
>     u'%s sbuffer org:todo/%d' % (prompt_pos, d.bufnr, )).encode(u'utf-8'))
> vim.error: Vim(python):Traceback (most recent call last):

my `g:org_todo_keywords` var is set to: `['TODO(t)', '|', 'DONE(d)']`

**Comment by Liriel** [comment]
on windows buffer names are separated by a backslash - fixed by looking for the last number in the buffer name instead of splitting
