### ISSUE TITLE
No tag autocompletion

### ISSUE THREAD

**Issue by memeplex** [jceb/vim-orgmode#299]
When trying to autocomplete tags in the current file using tab I get:

```
Error detected while processing :
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/carlos/.vim/bundle/vim-orgmode/ftplugin/orgmode/plugins/TagsProperties.py", line 106, in find_tags
    tags = vim.eval(u'input("Find Tags: ", "", "customlist,Org_complete_tags")')
vim.error: Vim(python):Traceback (most recent call last):
```

**Comment by doak** [comment]
Duplicate of #247.
