### ISSUE TITLE
Python 3.7 failure to run

### ISSUE THREAD

**Issue by cuongtranx** [jceb/vim-orgmode#303]
Updated to Python 3.7, some of the commands I used for checking off list don't work anymore. 

The change checkbox status cmd (cc) doesn't change the status, no error was thrown.

The add new checkbox cmd (cn) works, but not without throwing the following error.
 
```
Traceback (most recent call last):
  File "/Users/cuong.tran/.vim/plugged/vim-orgmode/ftplugin/orgmode/liborgmode/checkboxes.py", line 262, in all_children
    raise StopIteration()
StopIteration
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/cuong.tran/.vim/plugged/vim-orgmode/ftplugin/orgmode/plugins/EditCheckbox.py", line 134, in new_checkbox
    cls.update_checkboxes_status()
  File "/Users/cuong.tran/.vim/plugged/vim-orgmode/ftplugin/orgmode/plugins/EditCheckbox.py", line 218, in update_checkboxes_status
    cls._update_checkboxes_status(h.first_checkbox)
  File "/Users/cuong.tran/.vim/plugged/vim-orgmode/ftplugin/orgmode/plugins/EditCheckbox.py", line 235, in _update_checkboxes_status
    if c.all_children_status()[0] > 0:
  File "/Users/cuong.tran/.vim/plugged/vim-orgmode/ftplugin/orgmode/liborgmode/checkboxes.py", line 281, in all_children_status
    for c in self.all_children():
  File "/Users/cuong.tran/.vim/plugged/vim-orgmode/ftplugin/orgmode/liborgmode/checkboxes.py", line 267, in all_children
    for d in c.all_children():
  File "/Users/cuong.tran/.vim/plugged/vim-orgmode/ftplugin/orgmode/liborgmode/checkboxes.py", line 267, in all_children
    for d in c.all_children():
RuntimeError: generator raised StopIteration
```

**Comment by ivanperez-keera** [comment]
I can't even run it with python 3... :/

**Comment by akstrfn** [comment]
Can you check if this branch works for you?
https://github.com/akstrfn/vim-orgmode/tree/stopiter_fix

**Comment by ivanperez-keera** [comment]
I've been installed it using the "official" vba and `:so %`. How do I install it from the repo?

**Comment by akstrfn** [comment]
Try using https://github.com/junegunn/vim-plug

**Comment by cuongtranx** [comment]
Thanks, this fixes both of my issues.

@ivanperez-keera it's a forked repo, not this one so you might need to purge & install.
